import { buttonVariants } from "@/_components/ui/button";
import { Toaster } from "@/_components/ui/toaster";
import { ClerkProvider, SignedOut } from "@clerk/nextjs";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: {
    default: "Job Finder",
    template: "%s | Job Finder",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <body className="flex h-full flex-col antialiased">
          <Providers>
            <header className="shadow">
              <div className="container flex flex-row items-center justify-between p-4">
                <Link href="/" className="text-2xl font-bold">
                  Job Finder
                </Link>

                <nav className="flex flex-row items-center gap-4">
                  <SignedOut>
                    <Link
                      href="/sign-in"
                      className={buttonVariants({ variant: "outline" })}
                    >
                      Sign In
                    </Link>
                  </SignedOut>

                  <Link href="/job/new" className={buttonVariants()}>
                    Post Job
                  </Link>
                </nav>
              </div>
            </header>

            <main className="container flex-1 p-4">{children}</main>

            <footer>Footer</footer>

            <Toaster />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
