import { buttonVariants } from "@/_components/ui/button";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="p-4 shadow">
          <div className="container flex flex-row items-center justify-between">
            <Link href="/" className="text-2xl font-bold">
              Job Finder
            </Link>

            <nav className="flex flex-row items-center gap-4">
              <Link
                href="/sign-in"
                className={buttonVariants({ variant: "outline" })}
              >
                Sign In
              </Link>

              <Link href="/vacancy/new" className={buttonVariants()}>
                Post Vacancy
              </Link>
            </nav>
          </div>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
