name: Code Quality Checks Workflow
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check formatting
        run: bun run prettier:check
      - name: Check formatting with Prettier
        run: bun run prettier:check
      - name: Check for linting errors
        run: bun run lint
